import "express-async-errors";
import express, { NextFunction, Request, response, Response } from "express";
import { routes } from "./routes";
import { AppError } from "./errors/AppError";

const app = express();
app.use(express.json());
app.use(routes);
app.use(express.static("static"));
app.use((err: Error, req: Request, res: Response, next: NextFunction) => {
  if (err instanceof AppError) {
    return res.status(err.statusCode).json({
      status: "error",
      message: err.message,
    });
  }

  return response.status(500).json({
    status: "error",
    message: `Internal server error - ${err.message}`,
  });
});

app.listen(3000, () => console.log("Server is running"));
